sudo: required
services:
  - docker


before_install:
  - docker build -t alcpinto/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run alcpinto/react-test npm run test-coverage


after_success:
  - docker build -t alcpinto/multi-client ./client
  - docker build -t alcpinto/multi-nginx ./nginx
  - docker build -t alcpinto/multi-server ./server
  - docker build -t alcpinto/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push alcpinto/multi-client
  - docker push alcpinto/multi-nginx
  - docker push alcpinto/multi-server
  - docker push alcpinto/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-east-2
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: "elasticbeanstalk-us-east-2-002179058436"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY